# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Template
labels:
  application: kitchensink
metadata:
  annotations:
    description: Kitchensink application
    iconClass: icon-java
    tags: javaee,jboss,angularjs
  name: kitchensink-deploy
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}-${APPLICATION_ENV}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}-${APPLICATION_ENV}
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}-${APPLICATION_ENV}
          deploymentConfig: ${APPLICATION_NAME}-${APPLICATION_ENV}
        name: ${APPLICATION_NAME}-${APPLICATION_ENV}
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=${APPLICATION_NAME}-${APPLICATION_ENV}
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MQ_CLUSTER_PASSWORD
            value: ${MQ_CLUSTER_PASSWORD}
          - name: JGROUPS_CLUSTER_PASSWORD
            value: ${JGROUPS_CLUSTER_PASSWORD}
          - name: AUTO_DEPLOY_EXPLODED
            value: "false"
          - name: DB_SERVICE_PREFIX_MAPPING
            value: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql=DB
          - name: TX_DATABASE_PREFIX_MAPPING
            value: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql=DB
          - name: DB_JNDI
            value: java:jboss/datasources/KitchensinkAngularJSQuickstartDS
          - name: DB_USERNAME
            value: ${DB_USERNAME}
          - name: DB_PASSWORD
            value: ${DB_PASSWORD}
          - name: DB_DATABASE
            value: ${DB_DATABASE}
          image: ${APPLICATION_NAME}-${APPLICATION_ENV}
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /opt/eap/bin/jboss-cli.sh
                - -c
                - :shutdown(timeout=60)
          # livenessProbe:
          #   failureThreshold: 5
          #   httpGet:
          #     path: /
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 120
          #   periodSeconds: 5
          #   successThreshold: 1
          #   timeoutSeconds: 5
          name: ${APPLICATION_NAME}-${APPLICATION_ENV}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}-${APPLICATION_ENV}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:${APPLICATION_ENV}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The kitchensink application http port.
      service.alpha.openshift.io/dependencies: '[{"name":"${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql","namespace":"","kind":"Service"}]'
    labels:
      app: ${APPLICATION_NAME}-${APPLICATION_ENV}
    name: ${APPLICATION_NAME}-${APPLICATION_ENV}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}-${APPLICATION_ENV}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APPLICATION_NAME}-${APPLICATION_ENV}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${APPLICATION_NAME}-${APPLICATION_ENV}
      weight: 100
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The database server's port.
    labels:
      application: ${APPLICATION_NAME}-${APPLICATION_ENV}
    name: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql
  spec:
    ports:
    - port: 5432
      targetPort: 5432
    selector:
      deploymentConfig: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}-${APPLICATION_ENV}
    name: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}-${APPLICATION_ENV}
          deploymentConfig: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql
        name: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: ${DB_USERNAME}
          - name: POSTGRESQL_PASSWORD
            value: ${DB_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: ${DB_DATABASE}
          image: postgresql
          imagePullPolicy: Always
          # livenessProbe:
          #   initialDelaySeconds: 30
          #   tcpSocket:
          #     port: 5432
          #   timeoutSeconds: 1
          name: ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
            initialDelaySeconds: 5
            timeoutSeconds: 1
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}-${APPLICATION_ENV}-postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:latest
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
parameters:
- displayName: Application name
  name: APPLICATION_NAME
  value: ks
- displayName: Application environment
  name: APPLICATION_ENV
  value: test
- displayName: A-MQ cluster admin password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: MQ_CLUSTER_PASSWORD
  required: true
- displayName: JGroups cluster password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: JGROUPS_CLUSTER_PASSWORD
  required: true
- displayName: Database user name
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: DB_USERNAME
  required: true
- displayName: Database user password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: DB_PASSWORD
  required: true
- displayName: Application database
  name: DB_DATABASE
  value: kitchensinkdb
  required: true